export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    SOCIAL: '/auth/social',
    VERIFICATION_SEND: '/auth/verification/send',
    VERIFICATION_VERIFY: '/auth/verification/verify',
    VERIFICATION_RESEND: '/auth/verification/resend',
    CHANGE_PASSWORD: '/auth/change-password',
    SESSIONS: '/auth/sessions',
    SESSION: (id: number) => `/auth/sessions/${id}`,
    SESSIONS_OTHERS: '/auth/sessions/others',
    DELETE_ACCOUNT: '/auth/account',
  },
  USERS: {
    ME: '/users/me',
    ME_PROFILE: '/users/me/profile',
    GET: (id: number) => `/users/${id}`,
    GET_BY_HANDLE: (handle: string) => `/users/handle/${handle}`,
    GET_BY_NICKNAME: (nickname: string) => `/users/nickname/${nickname}`,
    FOLLOWERS: (id: number) => `/users/${id}/followers`,
    FOLLOWING: (id: number) => `/users/${id}/following`,
    FOLLOW: (id: number) => `/users/${id}/follow`,
    TIERS: (id: number) => `/users/${id}/tiers`,
    SUBSCRIBED: (creatorId: number) => `/users/${creatorId}/subscribed`,
    MY_TIER: (creatorId: number) => `/users/${creatorId}/my-tier`,
    BLOCKED: '/users/blocked',
    MUTED: '/users/muted',
    BLOCK: (id: number) => `/users/${id}/block`,
    MUTE: (id: number) => `/users/${id}/mute`,
    LIKED_POSTS: (id: number) => `/users/${id}/liked-posts`,
    COMMENTS: (id: number) => `/users/${id}/comments`,
    SETTINGS: '/users/settings',
  },
  POSTS: {
    CREATE: '/posts',
    GET: (id: number) => `/posts/${id}`,
    UPDATE: (id: number) => `/posts/${id}`,
    DELETE: (id: number) => `/posts/${id}`,
    LIKE: (id: number) => `/posts/${id}/like`,
    BOOKMARK: (id: number) => `/posts/${id}/bookmark`,
    REPOST: (id: number) => `/posts/${id}/repost`,
    COMMENTS: (id: number) => `/posts/${id}/comments`,
    CAN_ACCESS: (id: number) => `/posts/${id}/can-access`,
    USER_POSTS: (userId: number) => `/users/${userId}/posts`,
  },
  FEED: {
    UNIFIED: '/feed',
    HOME: '/feed/home',
    FOLLOWING: '/feed/following',
    CATEGORY: (categoryId: number) => `/feed/category/${categoryId}`,
  },
  COMMENTS: {
    BY_POST: (postId: number) => `/comments/post/${postId}`,
    CREATE: '/comments',
    UPDATE: (id: number) => `/comments/${id}`,
    DELETE: (id: number) => `/comments/${id}`,
    LIKE: (id: number) => `/comments/${id}/like`,
  },
  CATEGORIES: {
    LIST: '/categories',
    GET: (id: number) => `/categories/${id}`,
    SUBSCRIBE: (id: number) => `/categories/${id}/subscribe`,
  },
  BOOKMARKS: {
    LIST: '/bookmarks',
    ADD: '/bookmarks',
    REMOVE: (postId: number) => `/bookmarks/${postId}`,
    LISTS: '/bookmarks/lists',
    LIST_DETAIL: (listId: number) => `/bookmarks/lists/${listId}`,
    MOVE: (bookmarkId: number) => `/bookmarks/${bookmarkId}/move`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    READ: (id: number) => `/notifications/${id}/read`,
    READ_ALL: '/notifications/read-all',
    UNREAD_COUNT: '/notifications/unread-count',
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations',
    RECEIVED: '/messages/received',
    SENT: '/messages/sent',
    UNREAD_COUNT: '/messages/unread-count',
    GET: (id: number) => `/messages/${id}`,
    SEND: '/messages',
    READ: (id: number) => `/messages/${id}/read`,
    DELETE: (id: number) => `/messages/${id}`,
  },
  SEARCH: {
    ALL: '/search',
    TRENDING: '/search/trending',
  },
  FILES: {
    UPLOAD: '/files',
    UPLOAD_MULTIPLE: '/files/multiple',
    DOWNLOAD: (filename: string) => `/files/${filename}`,
  },
  PREMIUM: {
    STATUS: '/premium/status',
    SUBSCRIBE: '/premium/subscribe',
    CANCEL: '/premium/cancel',
  },
  FAN_TIERS: {
    LIST: '/users/tiers',
    CREATE: '/users/tiers',
    UPDATE: (tierId: number) => `/users/tiers/${tierId}`,
    DELETE: (tierId: number) => `/users/tiers/${tierId}`,
  },
  FAN_SUBSCRIPTIONS: {
    SUBSCRIBE: '/subscriptions/fan',
    MY_SUBSCRIPTIONS: '/subscriptions/fan/me',
    MY_SUBSCRIBERS: '/subscriptions/fan/subscribers',
  },
  SUPPORT: {
    TICKETS: '/support/tickets',
    REPORTS: '/support/reports',
    CATEGORY_REQUESTS: '/support/category-requests',
  },
  ADMIN: {
    STATS: '/admin/dashboard/stats',
    REPORTS: '/admin/reports',
    REPORT: (id: number) => `/admin/reports/${id}`,
    CATEGORY_REQUESTS: '/admin/category-requests',
    CATEGORY_REQUEST: (id: number) => `/admin/category-requests/${id}`,
    SUPPORT_TICKETS: '/admin/support-tickets',
    SUPPORT_TICKET: (id: number) => `/admin/support-tickets/${id}`,
    USERS: '/admin/users',
    USER_STATUS: (id: number) => `/admin/users/${id}/status`,
    POSTS: '/admin/posts',
    POST: (id: number) => `/admin/posts/${id}`,
  },
} as const;
